create table customer(customer_code int,
                      customer_name varchar(50),
                      contactperson_name varchar(50),
                      address varchar(100),
                      phone_number int(20),
                      mail_id varchar(50),
                      LKC_salesperson varchar(50),
                      visit_date date,
                      followup_date date,
                      customer_requirements varchar(500),
                      feedback varchar(500));


create table enquiry(customer_code int,
                     customer_name varchar(50),
                     service_request1 varchar(100),
                     mode varchar(20),
                     origin_port varchar(100),
                     delivery_port varchar(100),
                     no_ofpackage int,
                     weight int,
                     dimensions int,
                     commodity varchar(100),
                     termsof_shipment varchar(500),
                     invoice_no int,
                     invoice_value varchar(100),
                     service_request2 varchar(100)
                     ,currency varchar(100));


create table airimport(job_no int,
                       agent_name varchar(50),
                       MAWB_no int,
                       MAWB_date date,
                       HAWB_no int,
                       HAWB_date date,
                       no_ofpackage int,
                       g_weight int,
                       ch_weight int,
                       dimensions int,
                       commodity varchar(100),
                       termof_shipment varchar(100),
                       origin_port varchar(50),
                       destination_port varchar(50),
                       airlines_name varchar(50),
                       flight_no int,
                       flight_date date,
                       ETD varchar(100),
                       ETA varchar(100),
                       agentdebit_note varchar(100),
                       agentdebit_notedate date,
                       amount_1 int,
                       currency_1 varchar(100),
                       airlinedebit_note varchar(100),
                       airlinedebit_notedate date,
                       shipperinvoice_no int,
                       shipperinvoice_date date,
                       amount_2 int,
                       currency_2 varchar(100),
                       consol_manifest varchar(100),
                       airlinedoissued_ornot varchar(20),
                       CHA varchar(100),
                       boe_no int,
                       boe_date date);


create table airexport(job_no int,
					   co_loader varchar(50),
                       agent_name varchar(50),
						shipperbill_no int,
                       shipperbill_date date,
                       MAWB_no int,
                       MAWB_date date,
                       HAWB_no int,
                       HAWB_date date,
                       no_ofpackage int,
                       g_weight int,
                       ch_weight int,
                       dimensions int,
                       commodity varchar(100),
                       termof_shipment varchar(100),
                       origin_port varchar(50),
                       destination_port varchar(50),
                       airlines_name varchar(50),
                       flight_no int,
                       flight_date date,
                       ETD varchar(100),
                       ETA varchar(100),
                       agentdebit_note varchar(100),
                       agentdebit_notedate date,
                       amount_1 int,
                       currency_1 varchar(100),
                       airlinedebit_note varchar(100),
                       airlinedebit_notedate date,
                       shipperinvoice_no int,
                       amount_2 int,
                       currency_2 varchar(100),
                       consol_manifest varchar(100),
                       airlinedoissued_ornot varchar(20),
                       CHA varchar(100));


create table seaimport(job_no int,
					   co_loader varchar(50),
                       agent_name varchar(50),
						MBL_no int,
                       container_no int,
                       container_load varchar(100),
                       HBL_no int,
                       no_ofpackage int,
                       g_weight int,
                       CBM varchar(100),
                       dimensions int,
                       commodity varchar(100),
                       shipperinvoice_no1 int,
                       amount_1 int,
                       currency_1 varchar(100),
                       date_1 date,
                       agentdebit_note varchar(100),
                       date_2 date,
                       amount_2 int,
                       currency_2 varchar(100),
                       linerdebit_note varchar(100),
                       date_3 date,
                       CHA varchar(100),
                       date_4 date,
                       leoissued_ornot varchar(10),
                       EGM varchar(100),
                       shipperinvoice_no2 int,
                       IGM_controlmanifest varchar(100),
                       boe_no int,
                       date_5 date,
                       termsof_shipment varchar(100),
                       origin_port varchar(50),
                       destination_port varchar(50),
                       shipping_line varchar(100),
                       vessel_name varchar(50),
                       voyage_no int,
                       ETD varchar(100),
                       ETA varchar(100),
                       vesselberthing_date date);

        
create table seaexport(job_no int,
					   co_loader varchar(50),
						MBL_no int,
                        HBL_no int,
                       container_no int,
                       container_load varchar(100),
                       no_ofpackage int,
                        weight int,
                       CBM varchar(100),
                        dimensions int,
                       commodity varchar(100),
                       termsof_shipment varchar(100),
                       shipping_line varchar(100),
                       vessel_name varchar(100),
                       ETA varchar(100),
                       shipperinvoice_no int,
                       amount_1 int,
                       currency_1 varchar(100),
                       CHA varchar(100),
                       origin_port varchar(50),
                       delivery_port varchar(50),
                       shippingbill_no int,
                       date_1 date,
                       do_issuedornot varchar(50),
                       agentinvoice_no varchar(100),
                       date_2 date,
                       amount_2 int,
                       currency_2 varchar(100));








