CREATE TABLE customers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_code VARCHAR(50),
  customer_name VARCHAR(100),
  contact_person_name VARCHAR(100),
  address VARCHAR(255),
  phone_number VARCHAR(20),
  mail_id VARCHAR(100),
  lkc_sales_person VARCHAR(100),
  visit_date DATE,
  follow_up_date DATE,
  customer_requirements TEXT,
  feedback TEXT,
  pan VARCHAR(255),
  tan VARCHAR(255),
  aadhaar VARCHAR(255),
  telephone VARCHAR(255),
  bankCheque VARCHAR(255),
  creditForm VARCHAR(255),
  incorporation VARCHAR(255),
  gstForm VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
