CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,        -- Auto-incrementing user ID
  username VARCHAR(255) NOT NULL,           -- User's username
  password VARCHAR(255) NOT NULL,           -- User's hashed password
  email VARCHAR(255) NOT NULL UNIQUE,       -- User's email (unique)
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Timestamp for when the user is created
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP -- Timestamp for last update
);


CREATE TABLE Enquiries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    customer_code VARCHAR(50),
    customer_name VARCHAR(100),
    service_request VARCHAR(50),
    mode VARCHAR(50),
    origin_port VARCHAR(100),
    delivery_port VARCHAR(100),
    no_of_packages INT,
    weight DECIMAL(10, 2),
    dimensions VARCHAR(100),
    commodity VARCHAR(100),
    terms_of_shipment VARCHAR(100),
    invoice_no VARCHAR(50),
    invoice_value DECIMAL(10, 2),
    service_request2 VARCHAR(50),
    currency VARCHAR(10),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE air_import (
    id INT AUTO_INCREMENT PRIMARY KEY,
    job_no VARCHAR(50),
    agent_name VARCHAR(100),
    mawb_no VARCHAR(50),
    mawb_date DATE,
    hawb_no VARCHAR(50),
    hawb_date DATE,
    no_of_pkg INT,
    g_weight VARCHAR(50),
    ch_weight VARCHAR(50),
    dimensions VARCHAR(100),
    commodity VARCHAR(100),
    terms_of_shipment VARCHAR(100),
    origin_port VARCHAR(100),
    destination_port VARCHAR(100),
    airlines_name VARCHAR(100),
    flight_no VARCHAR(50),
    flight_date DATE,
    etd VARCHAR(50),
    eta VARCHAR(50),
    agent_debit_note VARCHAR(100),
    agent_debit_note_date DATE,
    agent_amount DECIMAL(10, 2),
    agent_currency VARCHAR(10),
    airline_debit_note VARCHAR(100),
    airline_debit_note_date DATE,
    shipper_invoice_no VARCHAR(100),
    shipper_invoice_date DATE,
    shipper_amount DECIMAL(10, 2),
    shipper_currency VARCHAR(10),
    consol_manifest VARCHAR(100),
    airline_do_issued VARCHAR(50)
);


CREATE TABLE sea_exports (
  id INT PRIMARY KEY AUTO_INCREMENT,
  job_no VARCHAR(50),
  co_loader VARCHAR(100),
  mbl_no VARCHAR(50),
  hbl_no VARCHAR(50),
  container_no VARCHAR(50),
  container_load ENUM('FCL', 'LCL'),
  no_of_package INT,
  weight DECIMAL(10,2),
  cbm DECIMAL(10,2),
  dimensions VARCHAR(100),
  commodity VARCHAR(200),
  terms_of_shipment VARCHAR(100),
  shipping_line VARCHAR(100),
  vessel_name VARCHAR(100),
  eta DATE,
  shipper_invoice_no VARCHAR(50),
  amount DECIMAL(10,2),
  currency VARCHAR(3),
  cha VARCHAR(100),
  origin_port VARCHAR(100),
  delivery_port VARCHAR(100),
  shipping_bill_no VARCHAR(50),
  shipping_bill_date DATE,
  do_issued ENUM('Yes', 'No'),
  agent_invoice_no VARCHAR(50),
  agent_invoice_date DATE,
  agent_amount DECIMAL(10,2),
  agent_currency VARCHAR(3),
  created_by VARCHAR(100),
  created_at TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  agent_name VARCHAR(100),
  gweight DECIMAL(10,2),
  dimension VARCHAR(100),
  date DATE,
  agent_debit_note VARCHAR(50),
  agent_debit_date DATE,
  agent_debit_amount DECIMAL(10,2),
  agent_debit_currency VARCHAR(10),
  liner_debit_note VARCHAR(50),
  liner_debit_date DATE,
  cha_date DATE,
  leo_issued ENUM('Yes', 'No'),
  egm VARCHAR(50),
  shipping_invoice_no VARCHAR(50),
  igm_control_manifest VARCHAR(50),
  boe_no VARCHAR(50),
  boe_date DATE,
  voyage_no VARCHAR(50),
  etd DATE,
  vessel_berthing_date DATE
);

CREATE TABLE air_exports (
  id INT PRIMARY KEY AUTO_INCREMENT,
  job_no VARCHAR(50),
  co_loader VARCHAR(100),
  agent_name VARCHAR(100),
  shipping_bill_no VARCHAR(50),
  shipping_bill_date DATE,
  mawb_no VARCHAR(50),
  mawb_date DATE,
  hawb_no VARCHAR(50),
  hawb_date DATE,
  no_of_package INT,
  gweight DECIMAL(10,2),
  chweight DECIMAL(10,2),
  dimensions VARCHAR(100),
  commodity VARCHAR(200),
  terms_of_shipment VARCHAR(100),
  origin_port VARCHAR(100),
  destination_port VARCHAR(100),
  airlines_name VARCHAR(100),
  flight_no VARCHAR(50),
  flight_date DATE,
  etd VARCHAR(50),
  eta VARCHAR(50),
  agent_debit_note VARCHAR(50),
  agent_debit_note_date DATE,
  amount DECIMAL(10,2),
  currency VARCHAR(10),
  airline_debit_note VARCHAR(50),
  airline_debit_note_date DATE,
  shipper_invoice_no VARCHAR(50),
  amount_invoice DECIMAL(10,2),
  currency_invoice VARCHAR(10),
  consol_manifest VARCHAR(100),
  airline_do_issued ENUM('Yes', 'No'),
  cha VARCHAR(100),
  created_by VARCHAR(100),
  created_at DATETIME,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);